site_name: DarkLord-W's Blog

theme:
  name: 'material'
  
  logo: https://avatars.githubusercontent.com/u/42199147   

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default  # 配色方案：浅色模式
      primary: indigo  # 原色
      accent: indigo   # 强调色
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
        
    # Dark mode       
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate   # 配色方案：深色模式
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
  # 启用左侧导航折叠
  navigation:
    collapse: true 

  # 页脚配置
  footer:
    copyright: "Powered By Darklord-W"
    links: []

  features:
    - navigation.sections   # 左导航分组，支持折叠
    - navigation.expand     # 自动展开当前目录
    # 不要 toc.integrate（避免文件内部标题插入左边导航）


# Markdown 扩展
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # 仅启用 H1 作为目录（禁止 H2/H3 出现在左侧）
  - toc:
      permalink: false
      toc_depth: 1


# 插件
plugins:
  - search
  - roamlinks
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags


extra:
  favicon: https://avatars.githubusercontent.com/u/42199147   
  generator: false  # 移除 "Made with Material for MkDocs"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
